name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Configure Poetry
      run: |
        echo "$(python -m site --user-base)/bin" >> $GITHUB_PATH
        echo "$(python -m site --user-base)/bin" >> $GITHUB_ENV

    - name: Install dependencies
      run: poetry install

    - name: Run pytest
      run: poetry run pytest
